"""Generate a ``langgraph.json`` manifest so ``agentship studio`` can open LangGraph Studio (§4.8).

We do not build a studio — we consume LangGraph Studio (``langgraph dev``). Studio loads graphs
named in a ``langgraph.json`` manifest, where each graph value is a Python import ref
(``module:attribute``). This module discovers the LangGraph agents under an ``agents/`` directory
and writes both the manifest and a small generated wrapper module that binds each agent's YAML spec
a compiled graph via the langgraph package's ``build_studio_graph`` factory.

Kept in ``agentship-core`` and vendor-free: it writes *text* (JSON + a Python file that references
the factory by string) and never imports LangGraph itself, so the manifest can be generated with
only the kernel installed. The factory it points at lives in ``agentship-langgraph``.
"""

from __future__ import annotations

import json
from pathlib import Path

from ..errors import AgentShipError
from ..spec import load_spec

#: The engine whose agents LangGraph Studio can render. Only these become manifest graphs.
LANGGRAPH_ENGINE = "langgraph"

#: The generated wrapper module (written next to the manifest) that binds specs → graphs.
WRAPPER_MODULE = "agentship_studio_graphs.py"

#: The langgraph-package factory the wrapper calls; referenced by string so core stays vendor-free.
GRAPH_FACTORY = "agentship_langgraph.studio:build_studio_graph"


def discover_langgraph_agents(agents_dir: Path) -> dict[str, Path]:
    """Map each LangGraph agent's name to its spec path, for every ``*.yaml`` under ``agents_dir``.

    Loads (and thereby validates) each spec, keeping only those whose engine is ``langgraph`` —
    Studio can render nothing else. Raises :class:`AgentShipError` when the directory is missing so
    the CLI can report an actionable message instead of writing an empty manifest.
    """
    if not agents_dir.is_dir():
        raise AgentShipError(f"agents directory not found: {agents_dir}")
    agents: dict[str, Path] = {}
    for path in sorted(p for p in agents_dir.iterdir() if p.suffix in (".yaml", ".yml")):
        spec = load_spec(path)
        if spec.engine == LANGGRAPH_ENGINE:
            agents[spec.name] = path.resolve()
    return agents


def _wrapper_source(agents: dict[str, Path]) -> str:
    """Render the generated wrapper module: one ``name = build_studio_graph("spec")`` per agent."""
    module, factory = GRAPH_FACTORY.split(":")
    lines = [
        '"""GENERATED by `agentship studio` — do not edit.',
        "",
        "Binds each discovered agent's YAML spec to a LangGraph graph for LangGraph Studio.",
        "Regenerated on every `agentship studio` run.",
        '"""',
        "",
        f"from {module} import {factory}",
        "",
    ]
    for name, spec_path in agents.items():
        lines.append(f"{name} = {factory}(r{str(spec_path)!r})")
    return "\n".join(lines) + "\n"


def generate_langgraph_json(agents_dir: Path, out: Path) -> Path:
    """Write a ``langgraph.json`` manifest (and its wrapper module) for the LangGraph agents.

    Discovers the LangGraph agents under ``agents_dir``, writes the generated wrapper module beside
    ``out``, and writes the manifest mapping each agent name to ``./<wrapper>:<name>``. Returns the
    manifest path. Raises :class:`AgentShipError` when no LangGraph agent is found, so
    ``agentship studio`` fails with a clear message rather than launching an empty Studio.
    """
    agents = discover_langgraph_agents(agents_dir)
    if not agents:
        raise AgentShipError(
            f"no LangGraph agents found in {agents_dir} — Studio only renders engine: langgraph"
        )

    out.parent.mkdir(parents=True, exist_ok=True)
    (out.parent / WRAPPER_MODULE).write_text(_wrapper_source(agents), encoding="utf-8")

    manifest = {
        "dependencies": ["."],
        "graphs": {name: f"./{WRAPPER_MODULE}:{name}" for name in agents},
        "env": ".env",
    }
    out.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return out
